# Generated by Django 4.0.7 on 2022-10-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='comments',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
