# Generated by Django 4.0.7 on 2022-11-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expenses_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='approval',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='rejected',
        ),
        migrations.AddField(
            model_name='expenses',
            name='approval_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
