# Generated by Django 4.0.7 on 2022-11-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_remove_expenses_approval_remove_expenses_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='approved_by',
            field=models.CharField(default='manual', max_length=50),
        ),
    ]
