# Generated by Django 4.0.7 on 2022-11-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expenses_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='approved_by',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
